# Generated by Django 5.1.4 on 2025-02-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_participants_event_rsvps'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='events-asset'),
        ),
    ]
