# Generated by Django 5.1.4 on 2025-02-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='events-asset/default-image.jpg', null=True, upload_to='events-asset'),
        ),
    ]
